name: Update GFG160 README

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install tabulate

    - name: Run README generator
      run: python .github/scripts/update_readme.py

    - name: Commit & Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Auto-update README progress table" || echo "No changes to commit"
        git push
